name: text_similarity
description: Implementation of Levenshtein's Automaton to find similarities between a String and a set of known words.
repository: https://github.com/pedrolemoz/text_similarity
version: 1.0.0

environment:
  sdk: ^3.1.2

dependencies:
  automata_theory: ^1.0.3

dev_dependencies:
  flutterando_analysis: ^0.0.2
  test: ^1.21.0
