name: text_similarity
description: Text Similarity
version: 1.0.0

environment:
  sdk: ^3.1.2

dependencies:
  automata_theory: ^1.0.3

dev_dependencies:
  flutterando_analysis: ^0.0.2
  test: ^1.21.0
